language: ruby
dist: trusty
rvm:
    - 2.4.1

cache:
    bundler: true
    directories:
        - .asset-cache/
        - .jekyll-cache/

script:
    - bundle exec jekyll build 

deploy:
    provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    local_dir: _site
    on:
        branch: master